### ISSUE TITLE
Linux Aarch64

### ISSUE THREAD

**Issue by KGrewal1** [conda-forge/eza-feedstock#30]
Would it be possible to produce builds for aarch64 Linux as well? (Would correspond to rust target aarch64-unknown-linux-gnu)

**Comment by synapticarbors** [comment]
Addressing via https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6661

**Comment by dbast** [comment]
done by https://github.com/conda-forge/eza-feedstock/pull/35
