### ISSUE TITLE
OSX arm64 build?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/eza-feedstock#5]
### Comment:

There's no arm build for this feedstock, so it can't be installed on Apple Silicon chips. (`brew` provides an arm build, so one _should_ be feasible, but is beyond me.) Any chance of an arm build?

**Comment by synapticarbors** [comment]
Sorry I missed this one. I just opened a PR here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5992

**Comment by synapticarbors** [comment]
closed by #12
